### ISSUE TITLE
Error while running run_lfnet.py

### ISSUE THREAD

**Issue by YvetteLaw** [vcg-uvic/lf-net-release#5]
I download the pretrained model and put them in the /release/models/.
However, while I running the run_lfnet.py, the /release/models/outdoor/config.pkl can't be opened correctly, see the following

Connected to pydev debugger (build 171.3780.115)
Traceback (most recent call last):
File "/home/jue/pycharm-community-2017.1/helpers/pydev/pydevd.py", line 1578, in 
globals = debugger.run(setup['file'], None, None, is_module)
File "/home/jue/pycharm-community-2017.1/helpers/pydev/pydevd.py", line 1015, in run
pydev_imports.execfile(file, globals, locals) # execute the script
File "/home/jue/Documents/LFNet_mine/run_lfnet.py", line 214, in 
raise ValueError('Fail to open {}'.format(config_path))
ValueError: Fail to open ./release/models/outdoor/config.pkl

**Comment by YvetteLaw** [comment]
I download the pretrained model and put them in the /release/models/. 
However, while I running the run_lfnet.py, the /release/models/outdoor/config.pkl can't be opened correctly, see the following

Connected to pydev debugger (build 171.3780.115)
Traceback (most recent call last):
  File "/home/jue/pycharm-community-2017.1/helpers/pydev/pydevd.py", line 1578, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jue/pycharm-community-2017.1/helpers/pydev/pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jue/Documents/LFNet_mine/run_lfnet.py", line 214, in <module>
    raise ValueError('Fail to open {}'.format(config_path))
ValueError: Fail to open ./release/models/outdoor/config.pkl

**Comment by YvetteLaw** [comment]
Emmm....how to close the
